# Generated by Django 3.2.3 on 2022-09-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_auto_20220908_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='room',
            new_name='room_id',
        ),
    ]
