# Generated by Django 3.2.3 on 2022-09-08 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_rename_room_vote_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='room_id',
            new_name='room',
        ),
    ]
